**Q1. Write a Python code to implement the KNN classifier algorithm on load_iris dataset in sklearn.datasets.**

In [56]:
from sklearn.datasets import load_iris
import pandas as pd
iris=load_iris()


In [57]:
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [58]:
# independent and dependent variable 
X=pd.DataFrame(iris.data,columns=iris.feature_names)
y=iris.target
X.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [59]:
## train test split
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.33,random_state=42)

In [60]:
# train model
from sklearn.neighbors import KNeighborsClassifier

classifier=KNeighborsClassifier(n_neighbors=5,algorithm='auto')
classifier.fit(X_train,y_train)
y_pred=classifier.predict(X_test)

In [61]:
# accuracy score
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

print(confusion_matrix(y_pred,y_test))
print(accuracy_score(y_pred,y_test))
print(classification_report(y_pred,y_test))

[[19  0  0]
 [ 0 15  1]
 [ 0  0 15]]
0.98
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      0.94      0.97        16
           2       0.94      1.00      0.97        15

    accuracy                           0.98        50
   macro avg       0.98      0.98      0.98        50
weighted avg       0.98      0.98      0.98        50



**Q2. Write a Python code to implement the KNN regressor algorithm on load_boston dataset in sklearn.datasets.**

In [81]:
from sklearn.datasets import load_boston
import warnings
warnings.filterwarnings('ignore')

boston = load_boston()
boston.keys()


dict_keys(['data', 'target', 'feature_names', 'DESCR', 'filename', 'data_module'])

In [82]:
# independent and dependent variable 
X=pd.DataFrame(boston.data,columns=boston.feature_names)
y=boston.target
X.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  
0     15.3  396.90   4.98  
1     17.8  396.90   9.14  
2     17.8  392.83   4.03  
3     18.7  394.63   2.94  
4     18.7  396.90   5.33

In [89]:
## train test split
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.23,random_state=42)

In [90]:
# train model
from sklearn.neighbors import KNeighborsRegressor

regressor=KNeighborsRegressor(n_neighbors=5,algorithm='auto')
regressor.fit(X_train,y_train)
y_pred=regressor.predict(X_test)

In [91]:
# accuracy score
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error
print(r2_score(y_pred,y_test))
print(mean_absolute_error(y_pred,y_test))
print(mean_squared_error(y_pred,y_test))

0.458848621956247
3.712820512820512
26.20374017094017


**Q3. Write a Python code snippet to find the optimal value of K for the KNN classifier algorithm using cross-validation on load_iris dataset in sklearn.datasets.**

In [98]:
from sklearn.model_selection import GridSearchCV
from sklearn.neighbors import KNeighborsClassifier

# independent and dependent variable 
X=pd.DataFrame(iris.data,columns=iris.feature_names)
y=iris.target

## train test split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.33,random_state=42)

#### hyperparameter tuning
import numpy as np

classifier=KNeighborsClassifier(n_neighbors=5,algorithm='auto')
param_grid={'n_neighbors':np.arange(1,51)}
grid=GridSearchCV(classifier, param_grid=param_grid, cv=5, scoring='accuracy')


In [100]:
grid.fit(X_train,y_train)
grid.best_params_


{'n_neighbors': 1}

**Q4. Implement the KNN regressor algorithm with feature scaling on load_boston dataset in sklearn.datasets.**


In [ ]:
# independent and dependent variable 
X=pd.DataFrame(boston.data,columns=boston.feature_names)
y=boston.target
X.head()

In [ ]:
## train test split
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.33,random_state=42)

In [70]:
## feature scalling
from sklearn.preprocessing import StandardScaler

scaler=StandardScaler()
X_train_scaled=scaler.fit_transform(X_train)
X_test_scaled=scaler.transform(X_test)

In [72]:
## model training
from sklearn.neighbors import KNeighborsRegressor

regressor=KNeighborsRegressor(n_neighbors=5,algorithm='auto')
regressor.fit(X_train_scaled,y_train)
y_pred=regressor.predict(X_test_scaled)

In [73]:
# accuracy score
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error
print(r2_score(y_pred,y_test))
print(mean_absolute_error(y_pred,y_test))
print(mean_squared_error(y_pred,y_test))

0.5686810579744874
2.714491017964072
19.066237125748508


**Q5. Write a Python code snippet to implement the KNN classifier algorithm with weighted voting on load_iris dataset in sklearn.datasets.**




In [75]:
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

# Load the iris dataset
iris = load_iris()
X = iris.data
y = iris.target

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create a KNN classifier with weighted voting
classifier = KNeighborsClassifier(n_neighbors=5, weights='distance',algorithm='auto')  

# Fit the classifier to the training data
classifier.fit(X_train, y_train)

# Make predictions on the test data
y_pred = classifier.predict(X_test)

# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)


Accuracy: 1.0


**Q6. Implement a function to standardise the features before applying KNN classifier.**

In [74]:

from sklearn.preprocessing import StandardScaler

def standardize_features(X):
    
    scaler = StandardScaler()
    standardized_X = scaler.fit_transform(X)
    return standardized_X, scaler


**Q7. Write a Python function to calculate the euclidean distance between two points.**

In [76]:
import math

def euclidean_distance(x1,y1,x2,y2):
    
    return math.sqrt((x2 - x1)**2 + (y2 - y1)**2)

# Example usage:
x1,y1,x2,y2=5,4,7,9
distance = euclidean_distance(x1,y1,x2,y2)
print("Euclidean Distance:", distance)


Euclidean Distance: 5.385164807134504


**Q8. Write a Python function to calculate the manhattan distance between two points.**

In [77]:
def manhattan_distance(x1,y1,x2,y2):
    return abs(x2-x1)+abs(y2-y1)

# Example usage:
x1,y1,x2,y2=5,4,7,9
distance = manhattan_distance(x1,y1,x2,y2)
print("Manhattan Distance:", distance)

Manhattan Distance: 7
