In [1]:
import numpy as np
import logging

logging.basicConfig(filename="week9.log",level=logging.DEBUG, format='%(asctime)s %(name)s %(levelname)s %(message)s')

In [2]:
list_ = [ '1' , '2' , '3' , '4', '5']
array_list = np.array(object = list_)

In [3]:
# Q1. Is there any difference in the data type of variables list_ and array_list? If there is then 
# write a code to print the data types of both the variables.

#list and array_list both are different because we can apeend element in list but we cannot append
# element in array_list
l=[1,2,3]
al=np.array([1,2,3,4])
print(type(l))
print(type(al))
logging.info(type(type(l)))
logging.info(type(al))

<class 'list'>
<class 'numpy.ndarray'>


In [4]:
# Q2. Write a code to print the data type of each and every element of both the variables list_ and
# arra_list.

for i in l:
    print(type(i))
al.dtype

<class 'int'>
<class 'int'>
<class 'int'>


dtype('int32')

In [5]:
# Q3. Considering the following changes in the variable, array_list:

array_list = np.array(object = list_, dtype = int)
logging.info(array_list)
array_list

array([1, 2, 3, 4, 5])

In [6]:
# Will there be any difference in the data type of the elements present in both the variables,
# list_ and arra_list? If so then print the data types of each and every element present in both
# the variables, list_ and arra_list.
for i in l:
    print(type(i))
array_list.dtype

<class 'int'>
<class 'int'>
<class 'int'>


dtype('int32')

In [7]:
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [8]:
# Q4. Write a code to find the following characteristics of variable, num_array:
# (i) shape
# return shate of array
print(array_list.shape)

# (ii) size:
#return no of element in array
print(array_list.size)

(5,)
5


In [9]:
# Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
# creation function.
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [10]:
# Q6. Create an identity matrix of shape (5,5) using numpy functions?
np.eye(5,5,dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])